version: '2.1'
services:
    webapp:
        build:
            context: ./services/webapp
            dockerfile: Dockerfile
            args:
                REACT_APP_ID: ${REACT_APP_ID}
                REACT_APP_NAME: ${REACT_APP_NAME}
        environment:
            REACT_APP_ID: ${REACT_APP_ID}
            REACT_APP_NAME: ${REACT_APP_NAME}
        ports:
            - ${HUMBLE_PORT}:8080
        restart: always

